[package]
authors = ["Ishan Dutta <ishandutta2007@gmail.com>"]
edition = "2024"
name = "sublime-rust"
version = "0.1.0"

[dependencies]
dirs = "3.0"
gpui = "=0.2.2"
libc = "0.2"
log = "0.4"
simplelog = "0.9"